import type { IndicatorDefinition } from '@/types/indicators';

export const INDICATORS: IndicatorDefinition[] = [
  {
    id: 'population',
    datasetId: 'demo_r_d2jan',
    label: 'Population',
    labelPt: 'População',
    unit: 'inhabitants',
    description: 'Total population on 1 January',
    category: 'demographics',
    colorScheme: 'sequential',
    higherIsBetter: true,
    decimals: 0,
  },
  {
    id: 'gdp',
    datasetId: 'nama_10r_2gdp',
    label: 'GDP',
    labelPt: 'PIB',
    unit: '€ millions',
    description: 'Gross Domestic Product at current market prices',
    category: 'economy',
    colorScheme: 'sequential',
    higherIsBetter: true,
    decimals: 1,
  },
  {
    id: 'unemployment',
    datasetId: 'lfst_r_lfu3rt',
    label: 'Unemployment Rate',
    labelPt: 'Taxa de Desemprego',
    unit: '%',
    description: 'Unemployment rate by NUTS 2 regions',
    category: 'labor',
    colorScheme: 'diverging',
    higherIsBetter: false,
    decimals: 1,
  },
  {
    id: 'hospital_beds',
    datasetId: 'hlth_rs_bdsrg',
    label: 'Hospital Beds',
    labelPt: 'Camas Hospitalares',
    unit: 'per 100k',
    description: 'Hospital beds per 100,000 inhabitants',
    category: 'health',
    colorScheme: 'sequential',
    higherIsBetter: true,
    decimals: 1,
  },
  {
    id: 'education',
    datasetId: 'edat_lfse_04',
    label: 'Tertiary Education',
    labelPt: 'Educação Superior',
    unit: '%',
    description: 'Population aged 25-64 with tertiary education',
    category: 'education',
    colorScheme: 'sequential',
    higherIsBetter: true,
    decimals: 1,
  },
  {
    id: 'income',
    datasetId: 'tgs00026',
    label: 'Disposable Income',
    labelPt: 'Rendimento Disponível',
    unit: '€ per capita',
    description: 'Primary income of private households per capita',
    category: 'income',
    colorScheme: 'sequential',
    higherIsBetter: true,
    decimals: 0,
  },
  {
    id: 'gdp_per_capita',
    datasetId: 'nama_10r_2gdp',
    label: 'GDP per Capita',
    labelPt: 'PIB per Capita',
    unit: '€',
    description: 'GDP per capita at current market prices',
    category: 'economy',
    colorScheme: 'sequential',
    higherIsBetter: true,
    decimals: 0,
  },
  {
    id: 'fertility',
    datasetId: 'demo_r_frate2',
    label: 'Fertility Rate',
    labelPt: 'Taxa de Fertilidade',
    unit: 'children/woman',
    description: 'Total fertility rate',
    category: 'demographics',
    colorScheme: 'diverging',
    higherIsBetter: true,
    decimals: 2,
  },
];

export const INDICATOR_MAP = new Map(
  INDICATORS.map((ind) => [ind.id, ind])
);

export const CATEGORIES = [
  { id: 'demographics', label: 'Demografia', icon: '👥' },
  { id: 'economy', label: 'Economia', icon: '💰' },
  { id: 'labor', label: 'Trabalho', icon: '👷' },
  { id: 'health', label: 'Saúde', icon: '🏥' },
  { id: 'education', label: 'Educação', icon: '🎓' },
  { id: 'income', label: 'Rendimento', icon: '💶' },
] as const;

export const DEFAULT_INDICATOR = 'population';
